# Generated by Django 4.2.9 on 2024-02-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_details', models.TextField()),
                ('movie_image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
